//! `gen-symbols` — 从 rustdoc JSON 生成符号索引
//!
//! 运行 `cargo rustdoc --output-format json` 获取每个 crate 的公开 API，
//! 然后后处理为 agent 友好的精简格式，输出到 `docs/engine/symbol-index.md`。

use std::collections::BTreeMap;
use std::fmt::Write;

use anyhow::Context;
use serde_json::Value;
use xshell::Shell;

const CRATES: &[CrateInfo] = &[
    CrateInfo {
        package: "vn-runtime",
        json_stem: "vn_runtime",
        src_prefix: "vn-runtime/src/",
    },
    CrateInfo {
        package: "host-dioxus",
        json_stem: "host_dioxus",
        src_prefix: "host-dioxus/src/",
    },
];

struct CrateInfo {
    package: &'static str,
    json_stem: &'static str,
    src_prefix: &'static str,
}

const OUTPUT_PATH: &str = "docs/engine/symbol-index.md";

pub fn gen_symbols(sh: &Shell) -> anyhow::Result<()> {
    let mut output = String::with_capacity(8192);
    writeln!(output, "# Symbol Index")?;
    writeln!(output)?;
    writeln!(
        output,
        "> Auto-generated by `cargo gen-symbols`. Do not edit manually."
    )?;
    writeln!(output)?;

    for ci in CRATES {
        eprintln!("\n==> Generating rustdoc JSON for {}...", ci.package);
        sh.cmd("cargo")
            .args([
                "rustdoc",
                "-p",
                ci.package,
                "--",
                "-Z",
                "unstable-options",
                "--output-format",
                "json",
            ])
            .run()
            .with_context(|| format!("cargo rustdoc failed for {}", ci.package))?;

        let json_path = format!("target/doc/{}.json", ci.json_stem);
        let raw = std::fs::read_to_string(&json_path)
            .with_context(|| format!("cannot read {json_path}"))?;
        let doc: Value =
            serde_json::from_str(&raw).with_context(|| format!("invalid JSON in {json_path}"))?;

        format_crate(&doc, ci, &mut output)?;
    }

    std::fs::write(OUTPUT_PATH, &output)?;
    eprintln!("\n==> Written {OUTPUT_PATH} ({} bytes)", output.len());
    Ok(())
}

// ── Per-crate formatting ────────────────────────────────────────────────

type FileMap = BTreeMap<String, Vec<SymbolEntry>>;
type Index<'a> = &'a serde_json::Map<String, Value>;

fn format_crate(doc: &Value, ci: &CrateInfo, out: &mut String) -> anyhow::Result<()> {
    let index = doc["index"]
        .as_object()
        .context("rustdoc JSON missing 'index'")?;

    let root_id = id_to_string(&doc["root"]);

    let mut by_file: FileMap = BTreeMap::new();
    walk_module(&root_id, index, ci, &mut by_file);

    writeln!(out, "## {}", ci.package)?;
    writeln!(out)?;

    for (file, mut items) in by_file {
        items.sort_by_key(|e| e.line);
        writeln!(out, "### {file}")?;
        for item in &items {
            writeln!(out, "{item}")?;
        }
        writeln!(out)?;
    }

    Ok(())
}

/// Walk the module tree, collecting only direct module-level items.
/// This naturally excludes impl methods.
fn walk_module(module_id: &str, index: Index<'_>, ci: &CrateInfo, by_file: &mut FileMap) {
    let Some(module_item) = index.get(module_id) else {
        return;
    };

    let Some(child_ids) = module_item["inner"]["module"]["items"].as_array() else {
        return;
    };

    for child_id_val in child_ids {
        let child_id = id_to_string(child_id_val);
        let Some(item) = index.get(&child_id) else {
            continue;
        };

        let inner = match item["inner"].as_object() {
            Some(obj) => obj,
            None => continue,
        };

        // Recurse into sub-modules
        if inner.contains_key("module") {
            walk_module(&child_id, index, ci, by_file);
            continue;
        }

        // Skip re-exports, imports, macros, etc.
        let entry = if inner.contains_key("struct") {
            make_struct_entry(item)
        } else if inner.contains_key("enum") {
            make_enum_entry(item, index)
        } else if inner.contains_key("trait") {
            make_trait_entry(item, index)
        } else if inner.contains_key("function") {
            make_fn_entry(item)
        } else if inner.contains_key("constant") {
            make_simple_entry(item, "const")
        } else if inner.contains_key("type_alias") {
            make_simple_entry(item, "type")
        } else {
            continue;
        };

        let Some(entry) = entry else { continue };

        let filename = normalize_path(item["span"]["filename"].as_str().unwrap_or(""));
        if !filename.starts_with(ci.src_prefix) {
            continue;
        }

        let rel = filename[ci.src_prefix.len()..].to_string();
        by_file.entry(rel).or_default().push(entry);
    }
}

// ── Item constructors ───────────────────────────────────────────────────

fn make_simple_entry(item: &Value, kind: &'static str) -> Option<SymbolEntry> {
    let name = item["name"].as_str()?;
    let line = span_start_line(&item["span"]);
    Some(SymbolEntry::simple(line, kind, name))
}

fn make_struct_entry(item: &Value) -> Option<SymbolEntry> {
    make_simple_entry(item, "struct")
}

fn make_fn_entry(item: &Value) -> Option<SymbolEntry> {
    make_simple_entry(item, "fn")
}

fn make_enum_entry(item: &Value, index: Index<'_>) -> Option<SymbolEntry> {
    let name = item["name"].as_str()?;
    let line = span_start_line(&item["span"]);
    let variant_ids = item["inner"]["enum"]["variants"].as_array()?;
    let variants: Vec<String> = variant_ids
        .iter()
        .filter_map(|vid| {
            let id = id_to_string(vid);
            let v = index.get(&id)?;
            v["name"].as_str().map(String::from)
        })
        .collect();
    Some(SymbolEntry::with_members(line, "enum", name, &variants))
}

fn make_trait_entry(item: &Value, index: Index<'_>) -> Option<SymbolEntry> {
    let name = item["name"].as_str()?;
    let line = span_start_line(&item["span"]);
    let method_ids = item["inner"]["trait"]["items"].as_array()?;
    let methods: Vec<String> = method_ids
        .iter()
        .filter_map(|mid| {
            let id = id_to_string(mid);
            let m = index.get(&id)?;
            let inner = m["inner"].as_object()?;
            if inner.contains_key("function") {
                m["name"].as_str().map(String::from)
            } else {
                None
            }
        })
        .collect();
    Some(SymbolEntry::with_members(line, "trait", name, &methods))
}

// ── Data types ──────────────────────────────────────────────────────────

struct SymbolEntry {
    line: usize,
    kind: &'static str,
    name: String,
    members: Option<String>,
}

impl SymbolEntry {
    fn simple(line: usize, kind: &'static str, name: &str) -> Self {
        Self {
            line,
            kind,
            name: name.to_string(),
            members: None,
        }
    }

    fn with_members(line: usize, kind: &'static str, name: &str, members: &[String]) -> Self {
        let members = if members.is_empty() {
            None
        } else {
            Some(format!("{{ {} }}", members.join(", ")))
        };
        Self {
            line,
            kind,
            name: name.to_string(),
            members,
        }
    }
}

impl std::fmt::Display for SymbolEntry {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, ":{:<4} {} {}", self.line, self.kind, self.name)?;
        if let Some(m) = &self.members {
            write!(f, " {m}")?;
        }
        Ok(())
    }
}

// ── Helpers ─────────────────────────────────────────────────────────────

fn span_start_line(span: &Value) -> usize {
    span["begin"]
        .as_array()
        .and_then(|a| a.first())
        .and_then(|v| v.as_u64())
        .unwrap_or(0) as usize
}

/// Convert a rustdoc ID (integer or string) to an index key string.
fn id_to_string(v: &Value) -> String {
    match v {
        Value::Number(n) => n.to_string(),
        Value::String(s) => s.clone(),
        _ => String::new(),
    }
}

fn normalize_path(p: &str) -> String {
    p.replace('\\', "/")
}
